call_method:
  name: Call QRC Method
  description: |
    Invokes a method on a Q-SYS device using QRC. See the
    QRC Commands Documentation (https://q-syshelp.qsc.com/Index.htm#External_Control_APIs/QRC/QRC_Commands.htm)
    for more details
  target:
    device:
      integration: qsys_qrc
    entity:
      - integration: qsys_qrc
        domain: sensor
  fields:
    method:
      name: Method
      description: Name of the method to invoke
      required: True
      example: Component.Set
      selector:
        text:
    params:
      name: Parameters
      description: Parameters to the method
      example: |
        Name: my apm
        Controls:
        - Name: ent.xfade.gain
          Value: -100.0
          Ramp: 2.0
      default: { }
      selector:
        object:
reload:
