call_method:
  name: Call QRC Method
  description: Invokes a method on the Core using QRC.
  target:
    device:
      integration: qsys_qrc
    entity:
      integration: qsys_qrc_nonexistent
  fields:
    method:
      name: Method
      description: Name of the method to invoke
      required: True
      example: Component.Set
      selector:
        text:
    params:
      name: Parameters
      description: Parameters to the method
      example: |
        name: my apm
        controls:
        - name: ent.xfade.gain
          value: -100.0
          ramp: 2.0
      default: { }
      selector:
        object:
